# Generated by Django 4.2.7 on 2023-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.FileField(blank=True, null=True, upload_to='coffee/')),
                ('caffeine', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=3.0, max_digits=3)),
            ],
        ),
    ]
