# Generated by Django 4.2.7 on 2023-11-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_api', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='coffee_api.coffee'),
        ),
    ]
