# Generated by Django 4.2.7 on 2023-12-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='about_me',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
